language: ruby
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - "2.1" # latest 2.1.x
  - "2.2" # latest 2.2.x
  - "jruby-18mode"
  - "jruby-19mode"
script:
  ruby ./lib/argparser.rb
branches:
  except:
    - "trash"
